### ISSUE TITLE
Site User list needs to be pruned of old folks and reduce rights unless necessary

### ISSUE THREAD

**Issue by getmechamot** [getmechamot/website-Balloon-Juice-public#16]

**Comment by getmechamot** [comment]
For security's sake, only the appropriate people should have higher than Author. A user must be Editor to be able to Moderate comments, but very few should be admins.

And all former users who won't be coming back ever should have their user accounts removed. 

These names should also be removed as per #18

**Comment by getmechamot** [comment]
I already moved all non-admins to Editor. Good policy is to remove folks who won't be back. If you do, please let me know names so I can remove from
 Contact form, etc.

**Comment by getmechamot** [comment]
For the record Admins are:
John
Alain
Adam
Anne Laurie

**Comment by BalloonJuice** [comment]
Betty should be an admin.

**Comment by getmechamot** [comment]
Betty added.
