### ISSUE TITLE
Troll filter

### ISSUE THREAD

**Issue by thearchduke** [getmechamot/website-Balloon-Juice-public#27]
### Integrate cleek's troll filter
---
We should integrate cleek's troll filter into the default blog experience. (When you mouseover a comment it gives you a small 'block troll' button next to the commenter's name, and when clicked adds them to a list that replaces their comments with something like "trolling by [username]". It does this to replies as well ('reply by [username] to trolling by [blocked username]'). 

This could be folded into the page itself (the filter is currently a browser extension) without much hassle as it's already handled with javascript and localstorage. This would let all users create custom troll filters with ease, and it wouldn't require logins or cookies or anything either. This *does* however mean that the filter would be tied to a specific installation of a browser.

We could also make it available on the mobile site.

Dependencies:
* contact cleek for permission

**Comment by getmechamot** [comment]
On desktop and mobile, folks love it - thanks to Cleek and @thearchduke
