### ISSUE TITLE
Add Comment Numbers to replies

### ISSUE THREAD

**Issue by getmechamot** [getmechamot/website-Balloon-Juice-public#34]
http://optout.aboutads.info/#/

**Comment by thearchduke** [comment]
As somebody noted in the thread where it was brought up, comments added to/removed from moderation will wreck this.

**Comment by getmechamot** [comment]
True, but the comment number thing is weird. The real comment number is in the millions; what’s shows visually is just that, a visual cue. Since the plugin that adds those comment numbers does it, I figure we can at least grab the same number and perhaps see what logic is used to adjust that number as a moderated or other comment gets inserted.

 

In many cases, if I start to type a long comment and two folks type short ones, WP seems to insert my comment where it belongs, so it’s not just moderation that throws things.

**Comment by getmechamot** [comment]
Idea shelved; too many complications and not enough value.
