### ISSUE TITLE
Add instructions for comments to help new users even if no local data storage rules, formatting etc

### ISSUE THREAD

**Issue by getmechamot** [getmechamot/website-Balloon-Juice-public#35]

**Comment by thearchduke** [comment]
Commenting should be normal for people who don't want to use the advanced localstorage options like the troll filter. (Can we link here to the tickets for said commenting features?)

I was thinking this morning we should put the text for those features in a modal, but for basic use for accessibility reasons it should just be text on the screen.

**Comment by getmechamot** [comment]
Agreed. And yes, just # and Issue number makes it link, so #27

Yeah I liked what I did before but something changed because it didn’t work anymore. But basically a button to expand and show text and then to hide it again. That text being some helpful instructions (buttons, some basic instructions for helping first timers and tips on not getting auto-moderation or trash or spam, links to Lexicon, etc.)

**Comment by thearchduke** [comment]
Note to use Modernizr to bundle the HTML5/js-required features and just not load them if there's insufficient browser support

**Comment by getmechamot** [comment]
Preliminary launch aborted; apparently WP 4.8 changed something so I'll need to tweak the code. It showed up in two places. The one above the comments was expanded and non-interactive. The one below the comments was in the correct place. So I removed it. On the test site, it looks like a button now and not a text link. Weird.

**Comment by getmechamot** [comment]
Talked with @WaterGirl17  and she will work with another user to provide some additional Comment tips.

**Comment by getmechamot** [comment]
Add border to comment help when exposed; mouse should show clickable cursor.
Tweak help on pie filter.

**Comment by getmechamot** [comment]
Add to mobile site please

**Comment by getmechamot** [comment]
On both mobile and desktop.
